version: '3.1'

services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: user
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    hostname: localhost
