 version: '3.1'
 services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: user
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    hostname: localhost

version: "3.1"
services:
  server:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/user?useSSL=false
    networks:
      - spring-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql/mysql-server:5.7
    networks:
      - spring-network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=user
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

networks:
  spring-network:
