spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8082
  connectionTimeout: 20000

---
### local profile
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://mysqldb:3306/user?useSSL=false
    username: sa
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


security:
  jwtSecret: localSecret
  jwtExpiretionMs: 360000
  jwtRefreshExpirationInMs: 360000