spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:./userss
    username: sa
    #generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect


server:
  port: 8082
  connectionTimeout: 20000

security:
  jwtSecret: localSecret
  jwtExpiretionMs: 360000
  jwtRefreshExpirationInMs: 360000