spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/user
    username: sa
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    #generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8082
  connectionTimeout: 20000


security:
  jwtSecret: localSecret
  jwtExpiretionMs: 360000
  jwtRefreshExpirationInMs: 360000