spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8082
  connectionTimeout: 20000

---
### local profile
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: username
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver


security:
  jwtSecret: localSecret
  jwtExpiretionMs: 360000
  jwtRefreshExpirationInMs: 360000