spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:./users;AUTO_SERVER=TRUE
    username: sa
    #generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.H2Dialect

