spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:./user
    username: sa
    #generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect