spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: password
    #generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

